### ISSUE TITLE
Editing a post doesn't seem to allow an image description to be added

### ISSUE THREAD

**Issue by davidgeary** [elk-zone/elk#1344]
I created my first post with an image but forgot to add an image description.  So I edited the post, adding an extra hashtag, then clicked Edit on the image, added the description and clicked Apply.

 The new hashtag now appears but the image is still without a description (there's no 'Alt' button by the image) - see https://mas.to/@zudnick/109720447392698920

**Comment by patak-dev** [comment]
See https://github.com/mastodon/mastodon/pull/20878 (https://elk.zone/mastodon.social/@cheeaun/109720590999140639)

**Comment by Shinigami92** [comment]
I was affected as well by this issue.
Cannot add an alt text to an already uploaded image.

**Comment by patak-dev** [comment]
https://github.com/mastodon/mastodon/pull/20878 has been resolved, so we should be able to do this after Mastodon 4.1

**Comment by haayman** [comment]
my server has mastodon 4.1 running, but the alt-tag still cannot be edited. That is: it's not saved
