### ISSUE TITLE
Login doesn't work with Pleroma

### ISSUE THREAD

**Issue by vibragiel** [elk-zone/elk#934]
I can't login into my Pleroma instance just after Elk was updated to `v0.3.0`. It was working fine in earlier versions. The backend is Pleroma version `2.4.55-921-g20790c1d-develop`.

While being redirected back to `elk.zone` for the OAuth callback (URL `https://elk.zone/signin/callback?server=gabi.is&token=...&vapid_key=...`), this is what the Console is showing:

![image](https://user-images.githubusercontent.com/289617/211542690-4faed464-ded8-47de-8dcd-434333e6dbb3.png)

**Comment by sxzz** [comment]
Could you please provide a public server where I register an account and test it?

**Comment by vibragiel** [comment]
Just an update, with elk v0.5.0 this is what I now get:
![image](https://user-images.githubusercontent.com/289617/212693106-fe247bdd-6317-4850-aa3d-54295838eb4e.png)

**Comment by vibragiel** [comment]
Funnily enough, it works with Firefox in Android, but not in the desktop (tried with v0.6.0).

**Comment by sxzz** [comment]
@vibragiel It works on my side. Could you please provide more information about the issue?

**Comment by nemesio65** [comment]
To add to the discussion, it works on Chrome in Windows, but doesn't work on Firefox in Windows I receive the same statusCode:422 in the screenshot posted by vibragiel.

**Comment by sxzz** [comment]
Still cannot reproduce it 

Firefox: 109.0 (64-bit)
Elk: 0.6.1

**Comment by vibragiel** [comment]
Ok I was able to log in successfully by putting Firefox in Safe Mode, so it must be some extension or configuration that's causing trouble. I'll try to pinpoint exactly what.

**Comment by Sevichecc** [comment]
I get this problem when I am already logged in to the Pleroma instance in the same browser, when I am not logged in everything is fine.

**Comment by edimitchel** [comment]
I got the same issue by trying to login on an non-mastodon instance (Akkoma)
https://github.com/BDX-town/Akkoma/issues/33

**Comment by wakest** [comment]
@sxzz do you want the login to my test account https://fe.disroot.org/@wakest (its running Akkoma, the fork of Pleroma that is petty popular lately) happy to let you use the account if you need one for testing with...

**Comment by Fell** [comment]
Looks like this issue has been fixed in canary?
I was just able to log in successfully using https://main.elk.zone/ @ [bc78b50](https://github.com/elk-zone/elk/commit/bc78b50ee0472c99276c7f5dba279d4594dd458f)

My instance is Akkoma [3.5.0-0-gd9508474b](https://akkoma.dev/AkkomaGang/akkoma/commit/d9508474b).
I could log in using Firefox 109 on Windows 10 x64 as well as Iceraven (forked Firefox 108) on Android 13.
In both cases, I was still logged into the Akkoma instance.

**Comment by Sevichecc** [comment]
> Looks like this issue has been fixed in canary? I was just able to log in successfully using https://main.elk.zone/ @ [bc78b50](https://github.com/elk-zone/elk/commit/bc78b50ee0472c99276c7f5dba279d4594dd458f)
> 
> My instance is Akkoma [3.5.0-0-gd9508474b](https://akkoma.dev/AkkomaGang/akkoma/commit/d9508474b). I could log in using Firefox 109 on Windows 10 x64 as well as Iceraven (forked Firefox 108) on Android 13. In both cases, I was still logged into the Akkoma instance.

Still don't work work for me, my instance is Pleroma (2.5.0)

I'am using Brave(v1.47.171) & FireFox Developer Edition (v1.47.171)
<img width="683" alt="image" src="https://user-images.githubusercontent.com/91365763/214645769-2ad70e9f-19c5-409f-bc7d-c020f5769910.png">
<img width="1427" alt="image" src="https://user-images.githubusercontent.com/91365763/214645786-5dfa55b2-4428-4f04-8bee-f74ee8d77339.png">

**Comment by wakest** [comment]
still broken on newest canary build for me <img width="716" alt="image" src="https://user-images.githubusercontent.com/7890201/214652882-0633cc0c-a611-4f9a-a921-652da4b043bf.png">

running Pleroma fork (Akkoma and Mangane) 
[BDX-town/Mangane](https://github.com/BDX-town/Mangane)
(vnomadic-hermit-crab-f7f5408).

**Comment by vibragiel** [comment]
> Ok I was able to log in successfully by putting Firefox in Safe Mode, so it must be some extension or configuration that's causing trouble. I'll try to pinpoint exactly what.

I has nothing to do with the extensions. But when I tried deleting all the elk related storage from my Firefox (not just cookies but also Indexed DB and Local Storage entries), _then_ it started working. And it works too with a fresh Firefox install, so from my side this issue could be closed.

Can everyone else having issues try to remove cookies, Indexed DB and Local Storage for the elk domain?

![image](https://user-images.githubusercontent.com/289617/214842292-8434a0a0-3435-44fa-9b37-18d5eb287e28.png)

**Comment by wakest** [comment]
@vibragiel wonderful! I just deleted cookies only and that did it!

**Comment by boehs** [comment]
Closing because it seems this was resolved?

**Comment by floogulinc** [comment]
It still doesn't work for me. Still get
```json
{"url":"/api/DOMAIN/oauth/https%3A%2F%2Fmain.elk.zone","statusCode":422,"statusMessage":"Missing authentication code.","message":"Missing authentication code.","stack":""}
```

**Comment by Bunny-Head** [comment]
Same error here using Phoronix (Firefox) and even after deleting everything elk related from all the possible cache:

![image](https://user-images.githubusercontent.com/122626274/219864343-fd1d268a-f2cd-4168-8108-2bd36493f678.png)

**Comment by Retidurc** [comment]
What an infuriating Heisenbug this is.. 

Using the exact same version of Akkoma and Elk as my prod configuration, everything works on the test instances.
But as soon as I try to use Elk on my main instance, it doesn't. I'll try to increase the log levels on the prod akkoma instance to see what the heck is going on.


I

**Comment by roseyhead** [comment]
Just chipping in here in case this helps anyone. Note that i'd previously tested Elk on a Mastodon server, now running my own Akkoma instance.
Tried to log into Elk a couple of times over the past few weeks, always got that "missing authentication code" message.
Tried to log in just now, same error. Cleared Elk-related files in my cache and tried again, same message.
Logged out of Akkoma, tried logging into Elk, success!
Firefox 110.0.1 on Windows 11.

Same situation with Firefox on Android, I received errors logging in while I was logged into Akkoma (haven't recorded them sorry). Went to my home domain, logged out, went to elk.zone, logged in and it just worked.

**Comment by floogulinc** [comment]
I don't think this should be closed as it not working while signed in is still an issue.

**Comment by ymollard** [comment]
I met that issue until February 2023 approximately, then it fixed it by itself and worked so far until  yesterday night. I am now getting the HTTP 422 shown by @wakest above.

I tested on 2 web browsers (Firefox and Chromium), and both in normal and private navigation too, with the same result every time.

The admin of the Akkoma instance (bdx.town) reports that no update on the server has been made the last days, and Elk does not seem to have been updated either because the front says "last compiled the last month v0.9.7".

If you want to reproduce @sxzz @vibragiel try creating an account on https://bdx.town and login with Elk, I expect the issue to appear.

**Comment by paulo-roger** [comment]
> I don't think this should be closed as it not working while signed in is still an issue.

Exactly, the issue still persists, there is workaround, but still annoying.

**Comment by Cl0v1s** [comment]
bdx.town admin here mentioned by @ymollard (salut l'ami), we achieved to get stable login on Akkoma by adding "force_login=true" on the elk's /api/[server]/login calls 

https://github.com/BDX-town/elk/blob/main/elk/composables/sign-in.ts#L32

We still have users reporting being unable to login to iceshrimp/iceshrimp.net etc...

**Comment by shuuji3** [comment]
Thanks for the information! I also created a test account on bdx.town and tried to login with Elk, but encountered the same problem. I confirmed the above change allows me to login to the server.

Probably we can add the check to detect if the account is Akkoma/Pleroma or not and ensure always using `force_login=true` for those servers. Phanpy has server detection code like this: https://github.com/cheeaun/phanpy/blob/main/src/utils/supports.js

**Comment by yan-foto** [comment]
I can confirm this on Firefox: if you are already logged in in Akkoma on Firefox, the login fails.

Workaround: log out from akkoma -> login into elk -> log in into akkoma again
